# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://golangcode.top
date_format: "ordinal"
title: 够浪程序员
subtitle: "码农不学golang，还是不够浪！"
description: "李斌的个人博客"
keywords: 够浪, golangcode
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Bin li
organization: golangcode.top
organization_url: http://golangcode.top
github_username: binlihpu
location: Shanghai, China
email: binlihpu@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: binlihpu/binlihpu.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: binlihpu
    repo: blog-comments
    oauth:
        client_id: ffaa0b2187afef4c4686
        client_secret: 2a32bfb91b9ce9f1a95b84aa02853ea6d97523f2
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: binlihpu
    repo: binlihpu.github.io
    clientID: ffaa0b2187afef4c4686
    clientSecret: 2a32bfb91b9ce9f1a95b84aa02853ea6d97523f2
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-112186312-1
